/**
 * A synthetic mem0 store, for looking at the UI without a Qdrant instance.
 *
 * Nothing here is real: the profiles, memories and timestamps are invented so
 * the app can be run, screenshotted and reviewed on a machine with no mem0
 * data. It is never mixed with a real store — when the mock is on, the real
 * fetch is skipped entirely and the header says so.
 *
 * Enable with `VITE_MOCK=1 pnpm dev`, or by adding `?mock=1` to the URL.
 */

import type { Collection, MemPoint } from './qdrant'

export function mockEnabled(): boolean {
  if (import.meta.env.VITE_MOCK === '1') return true
  if (typeof location === 'undefined') return false
  // Only a truthy-looking value counts. A bare `?mock` (empty string) is treated
  // as on, since that is how a hand-typed flag usually arrives, but `?mock=0`
  // is not — a link carrying `mock=0` clearly means "not the mock".
  const v = new URLSearchParams(location.search).get('mock')
  return v !== null && v !== '0' && v !== 'false'
}

const T = (iso: string): Record<string, unknown> => ({
  created_at: iso,
  updated_at: iso
})

function mem(
  id: string,
  userId: string,
  agentId: string,
  data: string,
  extra: Record<string, unknown> = {}
): MemPoint {
  return { id, payload: { user_id: userId, agent_id: agentId, data, ...extra } }
}

const MEMORIES: MemPoint[] = [
  mem(
    '1a4f0c58-6f0f-4a2e-9d3f-30b0f3a51c11',
    'demo-local',
    'assistant',
    'Prefers concise answers — no preamble, no restating the question, no summary of what was just said.',
    { channel: 'cli', attributed_to: 'user', hash: '6f1c9b2a4d0e8f37', ...T('2026-09-18T08:41:12.000Z') }
  ),
  mem(
    '2b7c1d69-7a1b-4c3d-8e4a-41c1a4b62d22',
    'demo-local',
    'assistant',
    'Runs Postgres 16 locally. Migrations live in db/migrations and are applied with make migrate; never hand-edit a applied migration.',
    { channel: 'cli', role: 'user', hash: '7a2d0c3b5e1f9a48', ...T('2026-09-18T09:02:44.000Z') }
  ),
  mem(
    '3c8d2e7a-8b2c-4d4e-9f5b-52d2b5c73e33',
    'demo-local',
    'assistant',
    'Deploys the staging API behind a shared reverse proxy on port 8443; TLS certificates renew through ACME and are reloaded without a restart.',
    { channel: 'telegram', attributed_to: 'assistant', hash: '8b3e1d4c6f2a0b59', ...T('2026-09-17T14:20:03.000Z') }
  ),
  mem(
    '4d9e3f8b-9c3d-4e5f-a06c-63e3c6d84f44',
    'demo-local',
    'assistant',
    'The build host has 8 cores. Keep each CI job under ten minutes or split it — the whole pipeline is expected to finish in one coffee.',
    { channel: 'web', attributed_to: 'user', hash: '9c4f2e5d7a3b1c60', ...T('2026-09-16T11:05:19.000Z') }
  ),
  mem(
    '5e0f4a9c-0d4e-4f60-b17d-74f4d7e95055',
    'demo-local',
    'assistant',
    'Decision: keep the retrieval layer behind an interface so the vector store can be swapped without touching the callers.',
    { channel: 'a2a', role: 'assistant', hash: '0d5a3f6e8b4c2d71', ...T('2026-09-15T16:47:51.000Z') }
  ),
  mem(
    '6f1a5b0d-1e5f-4061-a28e-85f5e8fa6166',
    'demo-local',
    'assistant',
    'Uses pnpm workspaces everywhere. Never npm or yarn in this repo — a second lockfile is treated as a bug.',
    { channel: 'cli', attributed_to: 'user', hash: '1e6b4a7f9c5d3e82', ...T('2026-09-15T07:58:20.000Z') }
  ),
  mem(
    '702b6c1e-2f60-4172-b39f-96f6f90b7277',
    'demo-local',
    'assistant',
    'Wants UTC in logs and local time in the interface. Mixing the two is the fastest way to lose an hour on a timestamp bug.',
    { channel: 'web', attributed_to: 'user', hash: '2f7c5b8a0d6e4f93', ...T('2026-09-14T19:12:07.000Z') }
  ),
  mem(
    '813c7d2f-3061-4283-c4a0-a7f7a01c8388',
    'demo-local',
    'assistant',
    'Weekly review happens Monday morning; the digest is generated by a scheduled job the night before and delivered to the usual channel.',
    { channel: 'telegram', attributed_to: 'assistant', migrated_from: 'legacy-export-v2', hash: '3098d6c9a1e7f5a4', ...T('2026-09-14T06:30:00.000Z') }
  ),
  mem(
    '924d8e30-4162-4394-d5b1-b808b12d9499',
    'demo-local',
    'assistant',
    'The interface uses a 4px spacing scale and exactly one accent colour. New components should not introduce a second one.',
    { channel: 'cli', attributed_to: 'user', hash: '41a9e7d0b2f8a6b5', ...T('2026-09-13T13:22:38.000Z') }
  ),
  mem(
    'a35e9f41-5273-44a5-e6c2-c919c23ea5aa',
    'demo-local',
    'assistant',
    'Long-form note: the ingest worker reads from a queue in batches of 512, writes embeddings in a single transaction per batch, and only then acknowledges. If a batch fails, the whole batch is retried — the queue is configured for at-least-once delivery, so every downstream consumer has to be idempotent. That trade-off was chosen deliberately over exactly-once, because the deduplication key is cheap and the operational complexity of transactional delivery across two systems was not worth it.',
    { channel: 'cli', attributed_to: 'assistant', hash: '52b0f8e1c3a9b7c6', ...T('2026-09-12T10:14:55.000Z') }
  ),
  mem(
    'b46f0a52-6384-45b6-f7d3-da2ad34fb6bb',
    'demo-local',
    'assistant',
    '',
    { channel: 'web', attributed_to: 'assistant', hash: '63c1a9f2d4b0c8d7', ...T('2026-09-11T21:40:11.000Z') }
  ),

  mem(
    'c5701b63-7495-46c7-a8e4-eb3be45ac7cc',
    'demo-local',
    'researcher',
    'Collects primary sources before secondary commentary. If a claim cannot be traced to something primary, it is marked as unverified rather than dropped.',
    { channel: 'cli', attributed_to: 'user', hash: '74d2b0a3e5c1d9e8', ...T('2026-09-18T07:15:02.000Z') }
  ),
  mem(
    'd6812c74-85a6-47d8-b9f5-fc4cf56bd8dd',
    'demo-local',
    'researcher',
    'Prefers tables over prose when comparing more than three options, and wants the trade-off column to say which option loses.',
    { channel: 'web', attributed_to: 'user', hash: '85e3c1b4f6d2e0f9', ...T('2026-09-17T09:33:26.000Z') }
  ),
  mem(
    'e7923d85-96b7-48e9-ca06-0d5d067ce9ee',
    'demo-local',
    'researcher',
    'The literature index is rebuilt nightly; anything published after the rebuild shows up the following morning.',
    { channel: 'telegram', attributed_to: 'assistant', hash: '96f4d2c5a7e3f1a0', ...T('2026-09-16T18:02:47.000Z') }
  ),
  mem(
    'f8a34e96-a7c8-49fa-db17-1e6e178dfa11',
    'demo-local',
    'researcher',
    'Asked for citations to be inline rather than footnoted, with the year in parentheses immediately after the claim.',
    { channel: 'cli', attributed_to: 'user', hash: 'a7f5a3d6b8f4a2b1', ...T('2026-09-15T12:26:13.000Z') }
  ),
  mem(
    '0a9b4fa7-b8d9-4a0b-ec28-2f7f289e0b22',
    'demo-local',
    'researcher',
    'Keeps a single running document per investigation rather than one file per source; the source list lives at the bottom of that document.',
    { channel: 'web', attributed_to: 'assistant', hash: 'b8a6b4e7c9a5b3c2', ...T('2026-09-14T15:48:39.000Z') }
  ),
  mem(
    '1bac50b8-c9ea-4b1c-fd39-3080390f1c33',
    'demo-local',
    'researcher',
    'Retracted a conclusion from the previous week after a primary source contradicted it; the correction is kept in place rather than deleted.',
    { channel: 'cli', attributed_to: 'assistant', migrated_from: 'legacy-export-v2', hash: 'c9b7c5f8d0b6c4d3', ...T('2026-09-13T08:07:24.000Z') }
  ),

  mem(
    '2cbd61c9-da0b-4c2d-0e4a-41914a0a2d44',
    'acme-labs',
    'support-bot',
    'Customers on the legacy plan keep their existing seat count until renewal; upgrades mid-term are pro-rated to the day.',
    { channel: 'a2a', role: 'user', hash: 'da0c8d6a1c7d5e4f', ...T('2026-09-18T10:55:31.000Z') }
  ),
  mem(
    '3dce72da-eb1c-4d3e-1f5b-52a25b1b3e55',
    'acme-labs',
    'support-bot',
    'Escalate anything mentioning data loss to the on-call engineer immediately, even outside business hours.',
    { channel: 'web', attributed_to: 'assistant', hash: 'eb1d9e7b2d8e6f50', ...T('2026-09-17T20:19:08.000Z') }
  ),
  mem(
    '4edf83eb-fc2d-4e4f-206c-63b36c2c4f66',
    'acme-labs',
    'support-bot',
    'The status page is the only source of truth during an incident; support answers point at it rather than describing the incident independently.',
    { channel: 'telegram', attributed_to: 'assistant', hash: 'fc2e0f8c3e9f7a61', ...T('2026-09-16T13:41:50.000Z') }
  ),
  mem(
    '5fe094fc-0d3e-4f50-317d-74c47d3d5077',
    'acme-labs',
    'support-bot',
    'Refunds under the threshold are approved without review; above it, the request goes to billing with the ticket reference attached.',
    { channel: 'a2a', attributed_to: 'user', hash: '0d3f108d4f0a8b72', ...T('2026-09-15T11:23:14.000Z') }
  ),
  mem(
    '60f1a50d-1e4f-4061-428e-85d58e4e6188',
    'acme-labs',
    'support-bot',
    'Do not promise a fix date. Say what is being investigated and when the customer will next hear from us.',
    { channel: 'cli', attributed_to: 'assistant', hash: '1e4a219e5a1b9c83', ...T('2026-09-14T09:36:57.000Z') }
  ),

  mem(
    '71a2b61e-2f50-4172-539f-96e69f5f7299',
    'sample-user',
    'web',
    'Keeps a paper notebook for planning and only moves a plan into the tool once it has survived a week.',
    { channel: 'web', attributed_to: 'user', hash: '2f5b32af6b2cad94', ...T('2026-09-18T06:11:45.000Z') }
  ),
  mem(
    '82b3c72f-3061-4283-64a0-a7f7a06a83aa',
    'sample-user',
    'web',
    'The calendar is shared with a partner; anything added there is assumed to be visible to both.',
    { channel: 'web', attributed_to: 'user', hash: '306c43b07c3dbea5', ...T('2026-09-16T17:29:22.000Z') }
  ),
  mem(
    '93c4d830-4172-4394-75b1-b808b17b94bb',
    'sample-user',
    'web',
    'Prefers a phone call over a meeting invite for anything under ten minutes.',
    { channel: 'telegram', attributed_to: 'user', hash: '417d54c18d4ecfb6', ...T('2026-09-13T19:03:36.000Z') }
  ),

  mem(
    'a4d5e941-5283-44a5-86c2-c919c28ca5cc',
    '',
    '',
    'Ungrouped point: no user_id or agent_id on this payload, which mem0 allows and every reader has to cope with.',
    { channel: 'cli', hash: '528e65d29e5fd0c7', ...T('2026-09-12T05:44:18.000Z') }
  )
]

const ENTITIES: MemPoint[] = [
  mem('b5e6fa52-6394-45b6-97d3-da2ad39db6dd', 'demo-local', 'assistant', 'Postgres 16', {
    entity_type: 'TOPIC',
    linked_memory_ids: ['2b7c1d69-7a1b-4c3d-8e4a-41c1a4b62d22']
  }),
  mem('c6f70b63-74a5-46c7-a8e4-eb3be4aec7ee', 'demo-local', 'assistant', 'pnpm workspaces', {
    entity_type: 'TOPIC',
    linked_memory_ids: ['6f1a5b0d-1e5f-4061-a28e-85f5e8fa6166']
  }),
  mem('d7081c74-85b6-47d8-b9f5-fc4cf5bfd811', 'demo-local', 'assistant', 'at-least-once delivery', {
    entity_type: 'TOPIC',
    linked_memory_ids: ['a35e9f41-5273-44a5-e6c2-c919c23ea5aa']
  }),
  mem('e8192d85-96c7-48e9-ca06-0d5d06c0e922', 'demo-local', 'researcher', 'primary sources', {
    entity_type: 'TOPIC',
    linked_memory_ids: ['c5701b63-7495-46c7-a8e4-eb3be45ac7cc']
  }),
  mem('f92a3e96-a7d8-49fa-db17-1e6e17d1fa33', 'acme-labs', 'support-bot', 'status page', {
    entity_type: 'TOPIC',
    linked_memory_ids: ['4edf83eb-fc2d-4e4f-206c-63b36c2c4f66']
  }),
  mem('0a3b4fa7-b8e9-4a0b-ec28-2f7f2802fb44', 'sample-user', 'web', 'notebook planning', {
    entity_type: 'TOPIC',
    linked_memory_ids: ['71a2b61e-2f50-4172-539f-96e69f5f7299']
  })
]

const STORE: Record<Collection, MemPoint[]> = {
  mem0: MEMORIES,
  mem0_entities: ENTITIES
}

/** Points for a collection in the mock store. Unknown collection → nothing. */
export const mockFetchAll = (collection: Collection): MemPoint[] =>
  STORE[collection] ?? []

export const mockCollectionInfo = (
  collection: Collection
): { points: number; dim: number | null } => ({
  points: STORE[collection]?.length ?? 0,
  dim: 1024
})
